services:
  web:
    ports:
      - "14141:8000"
    env_file:
      - .env.dev
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - .:/app
      - ./app/static/uploads:/app/static/uploads
    networks:
      - getoutside-net
      - nginx_net
      depends_on:
        - db
    restart: unless-stopped 

networks:
  getoutside-net:
    external: true
  nginx_net:
    external: true
